#!/usr/bin/env python3
# Copyright (c) 2026 PAL Robotics S.L. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Export the full model's collision model to YAML for the ROS simulation.

``kangaroo_full_constants.py`` is the source of truth for the Kangaroo full
model's contact geometry: ``_FRAMES`` (the massless carrier bodies) and
``_CAPSULES`` (the 27 collision capsules), applied to the generated MJCF by
``_replace_collisions`` on every mjlab load.  The ROS simulation loads the same
generated MJCF but never runs that step, so without this table its feet are the
converter's cloned visual meshes instead of the capsules the policies trained
against.

This script writes that table to a YAML file the ROS side can consume
(``kangaroo_mujoco``'s ``apply_collision_model.py``), so both ends apply the
same contact geometry and a foot retune in training cannot silently fail to
reach the simulation.

The Python stays the source of truth; the YAML is derived.  Re-run this after
touching ``_FRAMES``, ``_CAPSULES`` or ``FULL_COLLISION``, and commit the
result.  ``--check`` compares without writing, so CI can fail on drift.

Usage::

    # Refresh the checked-in table:
    .venv/bin/python scripts/export_collision_table.py

    # Fail (exit 1) if the checked-in table is stale:
    .venv/bin/python scripts/export_collision_table.py --check
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from pal_mjlab.robots.pal_kangaroo_full.kangaroo_full_constants import (
  _CAPSULES,
  _COLLISION_CLASS,
  _COLLISION_GROUP,
  _COLLISION_MATERIAL,
  _FRAMES,
  FULL_COLLISION,
)

# Default destination: the ROS package that owns the generated full-model MJCF.
_DEFAULT_OUT = (
  Path(__file__).resolve().parents[2]
  / "kangaroo_simulation"
  / "kangaroo_mujoco"
  / "config"
  / "full_model_collisions.yaml"
)

_HEADER = """\
# Generated by pal_mjlab/scripts/export_collision_table.py -- DO NOT EDIT BY HAND.
#
# The Kangaroo full model's contact geometry, lifted from
# pal_mjlab/robots/pal_kangaroo_full/kangaroo_full_constants.py so the ROS
# simulation applies exactly what training applies. Edit the Python and re-run
# the exporter; `--check` fails if this file is stale.
"""


def _vec(values) -> list[float] | None:
  """Plain floats, so the YAML has no numpy/tuple tags in it."""
  return None if values is None else [float(v) for v in values]


def _frames() -> list[dict]:
  """The carrier bodies, kept in declaration order (parents before children)."""
  return [
    {
      "name": frame.name,
      "parent": frame.parent,
      "pos": _vec(frame.pos),
      "quat": _vec(frame.quat),
    }
    for frame in _FRAMES
  ]


def _capsules() -> list[dict]:
  """The capsules, each either ``fromto`` or ``pos``/``quat``/``half_length``."""
  out = []
  for capsule in _CAPSULES:
    entry = {
      "name": capsule.name,
      "body": capsule.body,
      "radius": float(capsule.radius),
    }
    if capsule.fromto is not None:
      entry["fromto"] = _vec(capsule.fromto)
    else:
      entry["pos"] = _vec(capsule.pos)
      entry["quat"] = _vec(capsule.quat)
      entry["half_length"] = float(capsule.half_length)
    out.append(entry)
  return out


def _as_rules(mapping) -> list[dict]:
  """Flatten a CollisionCfg ``{regex: value}`` field into ordered rules.

  ``CollisionCfg`` applies its per-field dicts by regex match; dict order is the
  precedence, so it is preserved here rather than re-sorted.
  """
  if not mapping:
    return []
  if not isinstance(mapping, dict):
    return [{"match": ".*", "value": mapping}]
  return [{"match": expr, "value": value} for expr, value in mapping.items()]


def _tuning() -> dict:
  """``FULL_COLLISION``'s per-geom overrides (condim, priority, friction)."""
  return {
    "geom_names_expr": list(FULL_COLLISION.geom_names_expr),
    "condim": _as_rules(getattr(FULL_COLLISION, "condim", None)),
    "priority": _as_rules(getattr(FULL_COLLISION, "priority", None)),
    "friction": [
      {"match": rule["match"], "value": _vec(rule["value"])}
      for rule in _as_rules(getattr(FULL_COLLISION, "friction", None))
    ],
  }


def build_table() -> dict:
  return {
    "collision_class": _COLLISION_CLASS,
    "collision_group": int(_COLLISION_GROUP),
    "material": {"name": _COLLISION_MATERIAL, "rgba": [1.0, 0.65, 0.0, 0.2]},
    "frames": _frames(),
    "capsules": _capsules(),
    "tuning": _tuning(),
  }


def render(table: dict) -> str:
  return _HEADER + yaml.safe_dump(table, sort_keys=False, default_flow_style=None)


def main() -> int:
  parser = argparse.ArgumentParser(
    description=__doc__,
    formatter_class=argparse.RawDescriptionHelpFormatter,
  )
  parser.add_argument(
    "-o", "--output", type=Path, default=_DEFAULT_OUT, help="destination YAML"
  )
  parser.add_argument(
    "--check",
    action="store_true",
    help="compare against the destination and exit 1 if it differs",
  )
  args = parser.parse_args()

  rendered = render(build_table())

  if args.check:
    if not args.output.exists():
      print(f"MISSING: {args.output}", file=sys.stderr)
      return 1
    if args.output.read_text() != rendered:
      print(
        f"STALE: {args.output} does not match kangaroo_full_constants.py.\n"
        "Re-run scripts/export_collision_table.py and commit the result.",
        file=sys.stderr,
      )
      return 1
    print(f"up to date: {args.output}")
    return 0

  args.output.parent.mkdir(parents=True, exist_ok=True)
  args.output.write_text(rendered)
  table = build_table()
  print(
    f"wrote {args.output} "
    f"({len(table['frames'])} frames, {len(table['capsules'])} capsules)"
  )
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
