"""PAL Robotics Kangaroo (full-model) constants.

The MJCF is generated by ``kangaroo_simulation`` (``mujoco_description_formatted.xml``)
and copied here verbatim, so every name below has to track that generator. Joint,
actuator and geom names all changed in the 2026-08 regeneration; ``_normalize_spec``
holds the fix-ups applied on load so the copied XML can stay unmodified -- the
collision model included, which is built in ``_replace_collisions`` rather than
hand-edited into the copy.
"""

import re
from pathlib import Path
from typing import NamedTuple

import mujoco
import numpy as np
import torch
from mjlab.actuator import BuiltinPositionActuatorCfg
from mjlab.entity import EntityArticulationInfoCfg, EntityCfg
from mjlab.utils.spec_config import CollisionCfg
from pal_mjlab import PAL_MJLAB_SRC_PATH

##
# MJCF and assets.
##

_LEG_ACTUATORS_EFFORT_LIMITS = [5000.0, 2000.0]  # [LEG LENGTH, OTHERS]

KANG_FULL_XML: Path = (
  PAL_MJLAB_SRC_PATH / "robots" / "pal_kangaroo_full" / "xmls" / "kangaroo_full.xml"
)
assert KANG_FULL_XML.exists()


# Hip (pitch, roll) feasible region.
#
# Same points as pal_kangaroo's, with the roll column negated: the full model's
# hip roll turns the opposite way. Driving ``left_hip_xy`` by +0.1 rad swings the
# femur -9.3 mm in Y, where +0.1 rad on the simple model's ``leg_left_3_joint``
# -- which these points were measured against -- swings it +8.7 mm. Pitch agrees
# (-8.9 mm vs -9.0 mm in X), so only the second column flips. The region is not
# symmetric in roll (-0.413 .. +0.467), so leaving it unflipped would hold the
# leg to a mirrored region. scipy rebuilds the hull, so the winding change is
# irrelevant.
HIP_XY_CONVEX_HULL_POINTS = torch.tensor(
  [
    [-0.742, 0.035],
    [-0.742, -0.094],
    [-0.742, -0.167],
    [-0.707, -0.243],
    [-0.655, -0.349],
    [-0.61, -0.411],
    [-0.344, -0.413],
    [-0.061, -0.41],
    [0.307, -0.404],
    [0.486, -0.4],
    [0.55, -0.354],
    [0.638, -0.282],
    [0.709, -0.186],
    [0.72, -0.081],
    [0.722, 0.054],
    [0.708, 0.18],
    [0.641, 0.301],
    [0.531, 0.389],
    [0.448, 0.45],
    [0.171, 0.453],
    [-0.164, 0.455],
    [-0.434, 0.461],
    [-0.605, 0.467],
    [-0.659, 0.404],
    [-0.713, 0.309],
    [-0.742, 0.222],
    [-0.742, 0.133],
  ]
) * torch.tensor([1.0, -1.0])  # (pitch, roll) -> roll flipped, see above

ANKLE_XY_CONVEX_HULL_POINTS = torch.tensor(
  [
    [0.707, 0.005],
    [0.648, 0.112],
    [0.576, 0.23],
    [0.484, 0.38],
    [0.443, 0.439],
    [0.266, 0.443],
    [0.008, 0.441],
    [-0.293, 0.45],
    [-0.46, 0.448],
    [-0.505, 0.379],
    [-0.594, 0.244],
    [-0.686, 0.098],
    [-0.744, 0.001],
    [-0.688, -0.099],
    [-0.604, -0.231],
    [-0.499, -0.394],
    [-0.445, -0.472],
    [-0.254, -0.469],
    [0.005, -0.462],
    [0.232, -0.456],
    [0.429, -0.46],
    [0.475, -0.382],
    [0.583, -0.207],
    [0.665, -0.071],
  ]
)


NATURAL_FREQ = 10 * 2.0 * 3.1415926535  # 10Hz
DAMPING_RATIO = 2.0
FACTOR = 0.05


def _calc_actuator_params(
  gear_ratio: float, motor_inertia: float, effort: float
) -> dict:
  """Calculate armature, stiffness, and damping for an actuator."""
  armature = FACTOR * motor_inertia * gear_ratio**2
  stiffness = round(armature * NATURAL_FREQ**2, 3)
  damping = round(2.0 * DAMPING_RATIO * armature * NATURAL_FREQ, 3)
  return {
    "armature": armature,
    "stiffness": stiffness,
    "damping": damping,
    "effort_limit": effort,
  }


def _calc_leg_params(stiffness: float, effort: float) -> dict:
  """Calculate leg actuator parameters."""
  damping = round(2.0 * DAMPING_RATIO * stiffness / NATURAL_FREQ, 3)
  return {
    "armature": 0.01,
    "stiffness": stiffness,
    "damping": damping,
    "effort_limit": effort,
  }


# Motor parameters: (gear_ratio, motor_inertia, effort_limit)
S_PLUS = _calc_actuator_params(121, 1.728e-5, 50)


##
# Spec normalization.
#
# The generated MJCF is a standalone viewer scene: it ships a floor, a skybox and
# 22 <motor> actuators, and it leaves every robot geom unnamed. mjlab expects a
# bare robot (the scene supplies terrain and lighting), builds its own <position>
# actuators, and matches geoms by name, so all three are fixed up on load.
##

_COLLISION_GROUP = 3

# Torso IMU site, on pelvis_2_link. Same body and pose as the "imu" site the
# pre-2026-08 hand-written model carried, so root-state sensors read the same.
_IMU_SITE = "torso_imu_link"
_ROOT_BODY = "base_link"

# Scene-only assets bundled with the generated model.
_SCENE_GEOMS = ("floor",)
_SCENE_MATERIALS = ("groundplane",)
_SCENE_TEXTURES = ("groundplane", "")  # "" is the unnamed skybox.


def _name_geoms(spec: mujoco.MjSpec) -> None:
  """Name the generator's anonymous geoms, so regexes can select them.

  ``_replace_collisions`` runs first and names every capsule it adds, so this
  covers the ~90 visual meshes left over. mjlab's ``CollisionCfg`` looks geoms up
  by name and disables every geom it does not match, so leaving them anonymous
  makes that lookup collapse onto a single empty name.
  """
  for body in spec.bodies:
    counts: dict[str, int] = {}
    for geom in body.geoms:
      if geom.name:
        continue
      kind = "collision" if geom.group == _COLLISION_GROUP else "visual"
      index = counts.get(kind, 0)
      counts[kind] = index + 1
      geom.name = f"{body.name}_{kind}" + (f"_{index}" if index else "")


##
# Collision geometry.
#
# The generated MJCF carries no collision model of its own: the converter clones
# every visual mesh into a `collision` twin (90 of them), which is both far too
# expensive to simulate and far too detailed to be useful. Those are dropped on
# load and replaced by the capsule set below.
#
# 25 of the 27 capsules are lifted verbatim from the hand-written pal_kangaroo
# model (``robots/pal_kangaroo/xmls/kangaroo.xml``), so both robots present the
# same contact geometry to a policy. The two hip-xy motor capsules have no
# counterpart there: the simple model folds away the leg linkage that carries
# those bodies.
##

_VISUAL_CLASS = "visual"
_COLLISION_CLASS = "collision"
_VISUAL_MATERIAL = "dark_gray"
_COLLISION_MATERIAL = "bright_orange"


class _Frame(NamedTuple):
  """A massless carrier body the sole and ankle capsules hang off."""

  name: str
  parent: str
  pos: tuple[float, float, float] = (0.0, 0.0, 0.0)
  quat: tuple[float, float, float, float] = (1.0, 0.0, 0.0, 0.0)


class _Capsule(NamedTuple):
  """One collision capsule, in the local frame of ``body``.

  Given either by its two endpoints (``fromto``) or, for the capsules that came
  out of a mesh-fitting tool, by ``pos``/``quat``/``half_length``.
  """

  body: str
  name: str
  radius: float
  fromto: tuple[float, ...] | None = None
  pos: tuple[float, float, float] | None = None
  quat: tuple[float, float, float, float] | None = None
  half_length: float | None = None


def _leg_frames(side: str) -> tuple[_Frame, ...]:
  """The two carrier bodies pal_kangaroo hangs each foot's capsules off.

  These look removable -- they hold no joint, so they are welded to
  ``leg_*_5_link`` and can neither move nor collide independently -- but they are
  not. MuJoCo derives each contact's regularization from ``body_invweight0`` of
  the body owning the geom, and that is measured at the body's *own* origin:
  0.841 at ``leg_*_foot_link`` against 0.630 one body up. Re-expressing the
  capsules in ``leg_*_5_link`` reproduced every compiled geom pose to 1e-17 and
  still stiffened the foot contacts by 25%, so the frames are rebuilt here.
  """
  return (
    _Frame(
      f"leg_{side}_foot_link",
      f"leg_{side}_5_link",
      pos=(0.0, 0.0, -0.034),
      quat=(0.9848078, 0.0, -0.1736482, 0.0),
    ),
    _Frame(f"leg_{side}_ankle_link", f"leg_{side}_foot_link"),
  )


_FRAMES: tuple[_Frame, ...] = (*_leg_frames("left"), *_leg_frames("right"))


# Sole capsules in foot-frame coordinates; the numbering follows pal_kangaroo.
_SOLE_FROMTO: tuple[tuple[int, tuple[float, ...]], ...] = (
  (0, (-0.0830, -0.035, 0.0, 0.110, -0.0330, 0.0)),
  (2, (-0.0975, -0.021, 0.0, 0.120, -0.0215, 0.0)),
  (4, (-0.0985, -0.007, 0.0, 0.122, -0.0065, 0.0)),
  (6, (-0.0985, 0.007, 0.0, 0.122, 0.0065, 0.0)),
  (8, (-0.0975, 0.021, 0.0, 0.120, 0.0215, 0.0)),
  (10, (-0.0830, 0.035, 0.0, 0.110, 0.0330, 0.0)),
)


def _leg_capsules(side: str) -> tuple[_Capsule, ...]:
  """The capsules for one leg.

  Both legs use identical local coordinates -- the mirroring lives in the body
  frames, not in the numbers. Only the inboard hip-xy motor of each pair is
  covered: the pair sits 7 cm apart, so one capsule cannot reach both, and the
  inboard one is what the opposite leg can run into.
  """
  motor = f"{side}_hip_xy_motor_{'r' if side == 'left' else 'l'}"
  foot, ankle = f"leg_{side}_foot_link", f"leg_{side}_ankle_link"
  return (
    _Capsule(
      motor, f"{motor}_collision", 0.04, fromto=(-0.01, 0.0, -0.015, -0.01, 0.0, 0.0)
    ),
    _Capsule(
      f"{side}_femur",
      f"leg_{side}_femur_collision",
      0.08,
      pos=(0.03, 0.2, 0.0),
      quat=(0.0308436, 0.0308436, 0.7064338, 0.7064338),
      half_length=0.2,
    ),
    _Capsule(
      f"{side}_tibia",
      f"leg_{side}_knee_collision",
      0.04,
      fromto=(0.03896, 0.02628, 0.0, -0.16904, 0.24934, 0.0),
    ),
    _Capsule(
      f"{side}_tibia",
      f"leg_{side}_knee_bar_collision",
      0.05,
      fromto=(-0.063, 0.0, 0.0, -0.184, 0.23889, 0.0),
    ),
    *(
      _Capsule(foot, f"{side}_foot{i}_collision", 0.01, fromto=fromto)
      for i, fromto in _SOLE_FROMTO
    ),
    _Capsule(
      ankle,
      f"leg_{side}_ankle_collision",
      0.03,
      fromto=(-0.04, 0.0, 0.03, 0.02, 0.0, 0.03),
    ),
    _Capsule(
      ankle,
      f"leg_{side}_ankle_bar_collision",
      0.03,
      fromto=(-0.045, -0.035, 0.05, -0.045, 0.035, 0.05),
    ),
  )


_CAPSULES: tuple[_Capsule, ...] = (
  _Capsule(
    "pelvis_2_link",
    "pelvis_2_collision",
    0.163724,
    pos=(4.77798e-07, -1.67441e-06, 0.234507),
    quat=(1.0, -3.97075e-06, -1.19191e-05, 0.0),
    half_length=0.162985,
  ),
  _Capsule(
    "arm_left_4_link",
    "arm_left_4_collision",
    0.054849,
    pos=(0.210246, -0.0167497, -0.0171982),
    quat=(0.733112, 0.0532001, 0.678025, -2.2842e-07),
    half_length=0.219217,
  ),
  _Capsule(
    "arm_right_4_link",
    "arm_right_4_collision",
    0.0559132,
    pos=(0.210649, -0.0172373, -0.0265895),
    quat=(0.717524, 0.0513886, 0.694636, -1.38234e-06),
    half_length=0.220143,
  ),
  *_leg_capsules("left"),
  *_leg_capsules("right"),
)


def _style_visuals(spec: mujoco.MjSpec) -> None:
  """Register the two materials the copied XML lacks, and fix up the visuals.

  Visual geoms must not contribute mass. That is not cosmetic: ``torso_imu_link``
  is the one body the generator leaves without an ``<inertial>``, so its 5 mm
  marker box would otherwise weigh a gram at the default density of 1000.

  Applied per geom rather than to the ``visual`` default class, because MjSpec
  resolves classes onto elements at parse time -- editing the class after loading
  would only reach geoms added later, of which there are none.
  """
  existing = {material.name for material in spec.materials}
  if _VISUAL_MATERIAL not in existing:
    spec.add_material(name=_VISUAL_MATERIAL, rgba=[0.298039, 0.298039, 0.298039, 1.0])
  if _COLLISION_MATERIAL not in existing:
    spec.add_material(name=_COLLISION_MATERIAL, rgba=[1.0, 0.65, 0.0, 0.2])

  for body in spec.bodies:
    for geom in body.geoms:
      if geom.classname is None or geom.classname.name != _VISUAL_CLASS:
        continue
      geom.density = 0.0
      if not geom.material:  # the meshes carry their own; the marker box does not
        geom.material = _VISUAL_MATERIAL


def _require_body(spec: mujoco.MjSpec, name: str, wanted_by: str) -> mujoco.MjsBody:
  body = spec.body(name)
  if body is None:
    raise ValueError(
      f"{KANG_FULL_XML.name} has no body '{name}' to hang '{wanted_by}' off; "
      "body names last changed in the 2026-08 regeneration."
    )
  return body


def _replace_collisions(spec: mujoco.MjSpec) -> None:
  """Swap the converter's per-mesh collision twins for ``_CAPSULES``.

  The capsules are given ``density=0``: the bodies they hang off all declare an
  explicit ``<inertial>``, so geom-derived mass is ignored anyway, and a
  collision proxy has no business changing the robot's dynamics if that ever
  stops being true.

  ``FULL_COLLISION`` selects contact geoms by the ``.*_collision`` suffix, and
  ``_name_geoms`` hands that same suffix to any unnamed group-3 geom, so this
  ends by checking the collision group holds exactly the capsules -- a
  regenerated MJCF that grows a collision geom we did not put there fails loudly
  rather than quietly adding contact geometry to training.
  """
  generated = [
    geom
    for body in spec.bodies
    for geom in body.geoms
    if geom.classname is not None and geom.classname.name == _COLLISION_CLASS
  ]
  if not generated:
    raise ValueError(
      f"{KANG_FULL_XML.name} has no '{_COLLISION_CLASS}'-class geoms; the "
      "converter used to clone one per visual mesh -- check what it emits now "
      "before assuming the capsules below are the whole collision model."
    )
  for geom in generated:
    spec.delete(geom)

  for frame in _FRAMES:
    _require_body(spec, frame.parent, frame.name).add_body(
      name=frame.name, pos=frame.pos, quat=frame.quat
    )

  for capsule in _CAPSULES:
    body = _require_body(spec, capsule.body, capsule.name)
    shape = (
      {"fromto": capsule.fromto, "size": [capsule.radius, 0.0, 0.0]}
      if capsule.fromto is not None
      else {
        "pos": capsule.pos,
        "quat": capsule.quat,
        "size": [capsule.radius, capsule.half_length, 0.0],
      }
    )
    body.add_geom(
      name=capsule.name,
      type=mujoco.mjtGeom.mjGEOM_CAPSULE,
      group=_COLLISION_GROUP,
      contype=1,
      conaffinity=1,
      density=0.0,
      material=_COLLISION_MATERIAL,
      **shape,
    )

  in_group = {
    geom.name
    for body in spec.bodies
    for geom in body.geoms
    if geom.group == _COLLISION_GROUP
  }
  expected = {capsule.name for capsule in _CAPSULES}
  if in_group != expected:
    raise ValueError(
      "unexpected geoms in the collision group after replacement: "
      f"extra={sorted(in_group - expected)}, missing={sorted(expected - in_group)}"
    )


def _add_state_sensors(spec: mujoco.MjSpec) -> None:
  """Add the root-state sensors the velocity task observes.

  The generator emits only three IMU sensors (quat/gyro/accel), but the task's
  observations and mjlab's ``angular_momentum`` reward reference the set the
  previous hand-written model carried. The generated ``torso_imu_link`` site sits
  on ``pelvis_2_link`` at the same pose the old ``imu`` site did, so these read
  identically to before.

  Names and types match pal_kangaroo's hand-written model exactly, so the two
  robots can share observation configs -- and mjlab's own defaults, which ask for
  ``robot/imu_ang_vel`` and ``robot/imu_lin_vel``, resolve without an override.

  ``imu_ang_vel`` is a GYRO, i.e. angular velocity in the *site's* frame. That is
  what a real IMU reports; a FRAMEANGVEL would be world-frame and could not be
  fed from hardware without first estimating the base orientation.
  """
  existing = {sensor.name for sensor in spec.sensors}
  site = _IMU_SITE
  specs: tuple[tuple[str, mujoco.mjtSensor, mujoco.mjtObj, str], ...] = (
    ("imu_quat", mujoco.mjtSensor.mjSENS_FRAMEQUAT, mujoco.mjtObj.mjOBJ_SITE, site),
    ("imu_ang_vel", mujoco.mjtSensor.mjSENS_GYRO, mujoco.mjtObj.mjOBJ_SITE, site),
    (
      "imu_lin_vel",
      mujoco.mjtSensor.mjSENS_VELOCIMETER,
      mujoco.mjtObj.mjOBJ_SITE,
      site,
    ),
    (
      "imu_lin_acc",
      mujoco.mjtSensor.mjSENS_ACCELEROMETER,
      mujoco.mjtObj.mjOBJ_SITE,
      site,
    ),
    (
      "root_angmom",
      mujoco.mjtSensor.mjSENS_SUBTREEANGMOM,
      mujoco.mjtObj.mjOBJ_BODY,
      _ROOT_BODY,
    ),
  )
  for name, sensor_type, objtype, objname in specs:
    if name in existing:
      continue
    spec.add_sensor(name=name, type=sensor_type, objtype=objtype, objname=objname)


def _normalize_spec(spec: mujoco.MjSpec) -> mujoco.MjSpec:
  # Drop the XML's <motor> actuators; mjlab adds <position> actuators of its own
  # from KANG_FULL_ARTICULATION and does not remove pre-existing ones.
  for actuator in list(spec.actuators):
    spec.delete(actuator)

  # Drop the standalone viewer scene, which would duplicate mjlab's terrain.
  for geom in list(spec.worldbody.geoms):
    if geom.name in _SCENE_GEOMS:
      spec.delete(geom)
  for material in list(spec.materials):
    if material.name in _SCENE_MATERIALS:
      spec.delete(material)
  for texture in list(spec.textures):
    if texture.name in _SCENE_TEXTURES:
      spec.delete(texture)

  _style_visuals(spec)
  _replace_collisions(spec)
  _name_geoms(spec)
  _add_state_sensors(spec)
  return spec


def _load_spec(xml_path: Path) -> mujoco.MjSpec:
  return _normalize_spec(mujoco.MjSpec.from_file(str(xml_path)))


def get_kangaroo_spec() -> mujoco.MjSpec:
  return _load_spec(KANG_FULL_XML)


##
# Actuator config.
#
# The generated model numbers the prismatic ball-screw actuators per leg rather
# than naming them after the joint they drive:
#   1 -> hip yaw        2 -> hip xy left     3 -> hip xy right
#   4 -> ankle xy left  5 -> ankle xy right  length -> leg length
# Note the right leg declares 3 before 2, so ordinal position in the XML is not
# a reliable guide; these were matched by body and site membership.
##

KANG_FULL_HIP_Z_SLIDERS_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=(r"leg_(left|right)_1_actuator$",),
  **_calc_leg_params(16000.0, _LEG_ACTUATORS_EFFORT_LIMITS[1]),
)

KANG_FULL_HIP_XY_SLIDERS_L_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=(r"leg_(left|right)_2_actuator$",),
  **_calc_leg_params(16000.0, _LEG_ACTUATORS_EFFORT_LIMITS[1]),
)

KANG_FULL_HIP_XY_SLIDERS_R_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=(r"leg_(left|right)_3_actuator$",),
  **_calc_leg_params(16000.0, _LEG_ACTUATORS_EFFORT_LIMITS[1]),
)

KANG_FULL_ANKLE_XY_SLIDERS_L_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=(r"leg_(left|right)_4_actuator$",),
  **_calc_leg_params(16000.0, _LEG_ACTUATORS_EFFORT_LIMITS[1]),
)

KANG_FULL_ANKLE_XY_SLIDERS_R_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=(r"leg_(left|right)_5_actuator$",),
  **_calc_leg_params(16000.0, _LEG_ACTUATORS_EFFORT_LIMITS[1]),
)

KANG_FULL_LEG_LENGTH_SLIDERS_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=(r"leg_(left|right)_length_actuator$",),
  **_calc_leg_params(200000.0, _LEG_ACTUATORS_EFFORT_LIMITS[0]),
)

KANG_FULL_ARMS_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=(
    "arm_.*_1_joint",
    "arm_.*_2_joint",
    "arm_.*_3_joint",
    "arm_.*_4_joint",
  ),
  **S_PLUS,
)

KANG_FULL_PELVIS_1_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=("pelvis_1_joint",),
  **S_PLUS,
)

KANG_FULL_PELVIS_2_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=("pelvis_2_joint",),
  **S_PLUS,
)
##
# Keyframes.
##

_JOINT_NQ = {
  mujoco.mjtJoint.mjJNT_FREE: 7,
  mujoco.mjtJoint.mjJNT_BALL: 4,
  mujoco.mjtJoint.mjJNT_SLIDE: 1,
  mujoco.mjtJoint.mjJNT_HINGE: 1,
}


def _read_keyframe(
  key_name: str,
) -> tuple[tuple[float, float, float], dict[str, float]]:
  """Read a keyframe from the MJCF into ``(root_pos, {joint_regex: qpos})``.

  Kangaroo's legs are closed kinematic chains, so the passive linkage joints
  cannot be left at zero: the initial state has to sit on the constraint
  manifold, or the solver opens the reset by tearing the loops apart. mjlab
  defaults any joint absent from ``joint_pos`` to 0.0, so the pose has to be
  given in full — read it from the generator's keyframe rather than restating
  62 linkage angles here by hand.

  Keys are anchored regexes, not plain names: mjlab resolves ``joint_pos`` with
  ``re.match`` and takes the first hit, so a bare ``left_hip_xy_cross`` would
  also claim ``left_hip_xy_cross_l`` and silently mis-pose the linkage.

  Parses the spec only (no ``compile()``), so no meshes are loaded.
  """
  spec = mujoco.MjSpec.from_file(str(KANG_FULL_XML))
  key = next((k for k in spec.keys if k.name == key_name), None)
  if key is None:
    raise ValueError(
      f"{KANG_FULL_XML.name} has no '{key_name}' keyframe; "
      f"found {[k.name for k in spec.keys]}"
    )
  qpos = np.asarray(key.qpos)
  root_pos = (0.0, 0.0, 0.0)
  joint_pos: dict[str, float] = {}
  adr = 0
  for joint in spec.joints:
    nq = _JOINT_NQ[joint.type]
    if joint.type == mujoco.mjtJoint.mjJNT_FREE:
      root_pos = tuple(float(v) for v in qpos[adr : adr + 3])  # type: ignore[assignment]
    else:
      joint_pos[re.escape(joint.name) + "$"] = float(qpos[adr])
    adr += nq
  return root_pos, joint_pos


KANG_FULL_HOME_POS, KANG_FULL_HOME_JOINT_POS = _read_keyframe("home")

# The generator's "home" pose: base at 1.02 m, arms out, legs lightly bent. It
# covers all 82 non-free joints because the leg loops have to close; do not
# reduce it to the actuated subset, since mjlab zero-fills whatever is missing.
INIT_STATE = EntityCfg.InitialStateCfg(
  pos=KANG_FULL_HOME_POS,
  joint_pos=KANG_FULL_HOME_JOINT_POS,
  joint_vel={".*": 0.0},
)

##
# Collision config.
#
# The geoms these expressions select are the ones ``_replace_collisions`` builds
# from ``_CAPSULES``; nothing else in the model is left in the collision group.
##

# The six sole capsules per foot, named left_foot0_collision .. left_foot10_collision
# to match pal_kangaroo. Excludes the ankle capsules, which stay at condim 1.
_FOOT_REGEX = r"(left|right)_foot\d+_collision$"

FULL_COLLISION = CollisionCfg(
  geom_names_expr=(".*_collision",),
  condim={_FOOT_REGEX: 3, ".*_collision": 1},
  priority={_FOOT_REGEX: 1},
  friction={_FOOT_REGEX: (0.6,)},
)


KANG_FULL_ARTICULATION = EntityArticulationInfoCfg(
  actuators=(
    KANG_FULL_HIP_Z_SLIDERS_ACTUATOR_CFG,
    KANG_FULL_HIP_XY_SLIDERS_L_ACTUATOR_CFG,
    KANG_FULL_HIP_XY_SLIDERS_R_ACTUATOR_CFG,
    KANG_FULL_ANKLE_XY_SLIDERS_L_ACTUATOR_CFG,
    KANG_FULL_ANKLE_XY_SLIDERS_R_ACTUATOR_CFG,
    KANG_FULL_LEG_LENGTH_SLIDERS_ACTUATOR_CFG,
    KANG_FULL_ARMS_ACTUATOR_CFG,
    KANG_FULL_PELVIS_1_ACTUATOR_CFG,
    KANG_FULL_PELVIS_2_ACTUATOR_CFG,
  ),
  soft_joint_pos_limit_factor=0.99,
)


def get_kangaroo_full_robot_cfg() -> EntityCfg:
  return EntityCfg(
    init_state=INIT_STATE,
    collisions=(FULL_COLLISION,),
    spec_fn=get_kangaroo_spec,
    articulation=KANG_FULL_ARTICULATION,
  )


def _build_action_scales(
  articulation: EntityArticulationInfoCfg, exclude: set = frozenset()
) -> tuple[dict, tuple]:
  """Build action scale dict and actuator names from articulation config."""
  scales, names = {}, []
  for a in articulation.actuators:
    e = (
      a.effort_limit
      if isinstance(a.effort_limit, dict)
      else {n: a.effort_limit for n in a.target_names_expr}
    )
    s = (
      a.stiffness
      if isinstance(a.stiffness, dict)
      else {n: a.stiffness for n in a.target_names_expr}
    )
    for n in a.target_names_expr:
      if n in e and n in s and s[n] and n not in exclude:
        scales[n] = 0.25 * e[n] / s[n]
        names.append(n)
  return scales, tuple(names)


##
# Final config.
##

KANG_FULL_ACTION_SCALE, KANG_FULL_ACTUATOR_NAMES = _build_action_scales(
  KANG_FULL_ARTICULATION
)


if __name__ == "__main__":
  import mujoco.viewer as viewer
  from mjlab.entity.entity import Entity

  robot = Entity(get_kangaroo_full_robot_cfg())
  viewer.launch(robot.spec.compile())
