"""PAL Robotics Kangaroo (full-model) constants.

The MJCF is generated by ``kangaroo_simulation`` (``mujoco_description_formatted.xml``)
and copied here verbatim, so every name below has to track that generator. Joint,
actuator and geom names all changed in the 2026-08 regeneration; ``_normalize_spec``
holds the fix-ups applied on load so the copied XML can stay unmodified.
"""

import re
from pathlib import Path

import mujoco
import numpy as np
import torch
from mjlab.actuator import BuiltinPositionActuatorCfg
from mjlab.entity import EntityArticulationInfoCfg, EntityCfg
from mjlab.utils.spec_config import CollisionCfg
from pal_mjlab import PAL_MJLAB_SRC_PATH

##
# MJCF and assets.
##

_LEG_ACTUATORS_EFFORT_LIMITS = [5000.0, 2000.0]  # [LEG LENGTH, OTHERS]

KANG_FULL_XML: Path = (
  PAL_MJLAB_SRC_PATH / "robots" / "pal_kangaroo_full" / "xmls" / "kangaroo_full.xml"
)
assert KANG_FULL_XML.exists()


HIP_XY_CONVEX_HULL_POINTS = torch.tensor(
  [
    [-0.742, 0.035],
    [-0.742, -0.094],
    [-0.742, -0.167],
    [-0.707, -0.243],
    [-0.655, -0.349],
    [-0.61, -0.411],
    [-0.344, -0.413],
    [-0.061, -0.41],
    [0.307, -0.404],
    [0.486, -0.4],
    [0.55, -0.354],
    [0.638, -0.282],
    [0.709, -0.186],
    [0.72, -0.081],
    [0.722, 0.054],
    [0.708, 0.18],
    [0.641, 0.301],
    [0.531, 0.389],
    [0.448, 0.45],
    [0.171, 0.453],
    [-0.164, 0.455],
    [-0.434, 0.461],
    [-0.605, 0.467],
    [-0.659, 0.404],
    [-0.713, 0.309],
    [-0.742, 0.222],
    [-0.742, 0.133],
  ]
)

ANKLE_XY_CONVEX_HULL_POINTS = torch.tensor(
  [
    [0.707, 0.005],
    [0.648, 0.112],
    [0.576, 0.23],
    [0.484, 0.38],
    [0.443, 0.439],
    [0.266, 0.443],
    [0.008, 0.441],
    [-0.293, 0.45],
    [-0.46, 0.448],
    [-0.505, 0.379],
    [-0.594, 0.244],
    [-0.686, 0.098],
    [-0.744, 0.001],
    [-0.688, -0.099],
    [-0.604, -0.231],
    [-0.499, -0.394],
    [-0.445, -0.472],
    [-0.254, -0.469],
    [0.005, -0.462],
    [0.232, -0.456],
    [0.429, -0.46],
    [0.475, -0.382],
    [0.583, -0.207],
    [0.665, -0.071],
  ]
)


NATURAL_FREQ = 10 * 2.0 * 3.1415926535  # 10Hz
DAMPING_RATIO = 2.0
FACTOR = 0.05


def _calc_actuator_params(
  gear_ratio: float, motor_inertia: float, effort: float
) -> dict:
  """Calculate armature, stiffness, and damping for an actuator."""
  armature = FACTOR * motor_inertia * gear_ratio**2
  stiffness = round(armature * NATURAL_FREQ**2, 3)
  damping = round(2.0 * DAMPING_RATIO * armature * NATURAL_FREQ, 3)
  return {
    "armature": armature,
    "stiffness": stiffness,
    "damping": damping,
    "effort_limit": effort,
  }


def _calc_leg_params(stiffness: float, effort: float) -> dict:
  """Calculate leg actuator parameters."""
  damping = round(2.0 * DAMPING_RATIO * stiffness / NATURAL_FREQ, 3)
  return {
    "armature": 0.01,
    "stiffness": stiffness,
    "damping": damping,
    "effort_limit": effort,
  }


# Motor parameters: (gear_ratio, motor_inertia, effort_limit)
S_PLUS = _calc_actuator_params(121, 1.728e-5, 50)


##
# Spec normalization.
#
# The generated MJCF is a standalone viewer scene: it ships a floor, a skybox and
# 22 <motor> actuators, and it leaves every robot geom unnamed. mjlab expects a
# bare robot (the scene supplies terrain and lighting), builds its own <position>
# actuators, and matches geoms by name, so all three are fixed up on load.
##

_COLLISION_GROUP = 3

# Scene-only assets bundled with the generated model.
_SCENE_GEOMS = ("floor",)
_SCENE_MATERIALS = ("groundplane",)
_SCENE_TEXTURES = ("groundplane", "")  # "" is the unnamed skybox.


def _name_geoms(spec: mujoco.MjSpec) -> None:
  """Name the generator's anonymous geoms, so regexes can select them.

  The hand-written collision capsules carry names already; this covers the ~90
  auto-generated visual meshes. mjlab's ``CollisionCfg`` looks geoms up by name
  and disables every geom it does not match, so leaving them anonymous makes that
  lookup collapse onto a single empty name.
  """
  for body in spec.bodies:
    counts: dict[str, int] = {}
    for geom in body.geoms:
      if geom.name:
        continue
      kind = "collision" if geom.group == _COLLISION_GROUP else "visual"
      index = counts.get(kind, 0)
      counts[kind] = index + 1
      geom.name = f"{body.name}_{kind}" + (f"_{index}" if index else "")


def _normalize_spec(spec: mujoco.MjSpec) -> mujoco.MjSpec:
  # Drop the XML's <motor> actuators; mjlab adds <position> actuators of its own
  # from KANG_FULL_ARTICULATION and does not remove pre-existing ones.
  for actuator in list(spec.actuators):
    spec.delete(actuator)

  # Drop the standalone viewer scene, which would duplicate mjlab's terrain.
  for geom in list(spec.worldbody.geoms):
    if geom.name in _SCENE_GEOMS:
      spec.delete(geom)
  for material in list(spec.materials):
    if material.name in _SCENE_MATERIALS:
      spec.delete(material)
  for texture in list(spec.textures):
    if texture.name in _SCENE_TEXTURES:
      spec.delete(texture)

  _name_geoms(spec)
  return spec


def _load_spec(xml_path: Path) -> mujoco.MjSpec:
  return _normalize_spec(mujoco.MjSpec.from_file(str(xml_path)))


def get_kangaroo_spec() -> mujoco.MjSpec:
  return _load_spec(KANG_FULL_XML)


##
# Actuator config.
#
# The generated model numbers the prismatic ball-screw actuators per leg rather
# than naming them after the joint they drive:
#   1 -> hip yaw        2 -> hip xy left     3 -> hip xy right
#   4 -> ankle xy left  5 -> ankle xy right  length -> leg length
# Note the right leg declares 3 before 2, so ordinal position in the XML is not
# a reliable guide; these were matched by body and site membership.
##

KANG_FULL_HIP_Z_SLIDERS_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=(r"leg_(left|right)_1_actuator$",),
  **_calc_leg_params(16000.0, _LEG_ACTUATORS_EFFORT_LIMITS[1]),
)

KANG_FULL_HIP_XY_SLIDERS_L_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=(r"leg_(left|right)_2_actuator$",),
  **_calc_leg_params(16000.0, _LEG_ACTUATORS_EFFORT_LIMITS[1]),
)

KANG_FULL_HIP_XY_SLIDERS_R_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=(r"leg_(left|right)_3_actuator$",),
  **_calc_leg_params(16000.0, _LEG_ACTUATORS_EFFORT_LIMITS[1]),
)

KANG_FULL_ANKLE_XY_SLIDERS_L_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=(r"leg_(left|right)_4_actuator$",),
  **_calc_leg_params(16000.0, _LEG_ACTUATORS_EFFORT_LIMITS[1]),
)

KANG_FULL_ANKLE_XY_SLIDERS_R_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=(r"leg_(left|right)_5_actuator$",),
  **_calc_leg_params(16000.0, _LEG_ACTUATORS_EFFORT_LIMITS[1]),
)

KANG_FULL_LEG_LENGTH_SLIDERS_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=(r"leg_(left|right)_length_actuator$",),
  **_calc_leg_params(200000.0, _LEG_ACTUATORS_EFFORT_LIMITS[0]),
)

KANG_FULL_ARMS_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=(
    "arm_.*_1_joint",
    "arm_.*_2_joint",
    "arm_.*_3_joint",
    "arm_.*_4_joint",
  ),
  **S_PLUS,
)

KANG_FULL_PELVIS_1_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=("pelvis_1_joint",),
  **S_PLUS,
)

KANG_FULL_PELVIS_2_ACTUATOR_CFG = BuiltinPositionActuatorCfg(
  target_names_expr=("pelvis_2_joint",),
  **S_PLUS,
)
##
# Keyframes.
##

_JOINT_NQ = {
  mujoco.mjtJoint.mjJNT_FREE: 7,
  mujoco.mjtJoint.mjJNT_BALL: 4,
  mujoco.mjtJoint.mjJNT_SLIDE: 1,
  mujoco.mjtJoint.mjJNT_HINGE: 1,
}


def _read_keyframe(
  key_name: str,
) -> tuple[tuple[float, float, float], dict[str, float]]:
  """Read a keyframe from the MJCF into ``(root_pos, {joint_regex: qpos})``.

  Kangaroo's legs are closed kinematic chains, so the passive linkage joints
  cannot be left at zero: the initial state has to sit on the constraint
  manifold, or the solver opens the reset by tearing the loops apart. mjlab
  defaults any joint absent from ``joint_pos`` to 0.0, so the pose has to be
  given in full — read it from the generator's keyframe rather than restating
  62 linkage angles here by hand.

  Keys are anchored regexes, not plain names: mjlab resolves ``joint_pos`` with
  ``re.match`` and takes the first hit, so a bare ``left_hip_xy_cross`` would
  also claim ``left_hip_xy_cross_l`` and silently mis-pose the linkage.

  Parses the spec only (no ``compile()``), so no meshes are loaded.
  """
  spec = mujoco.MjSpec.from_file(str(KANG_FULL_XML))
  key = next((k for k in spec.keys if k.name == key_name), None)
  if key is None:
    raise ValueError(
      f"{KANG_FULL_XML.name} has no '{key_name}' keyframe; "
      f"found {[k.name for k in spec.keys]}"
    )
  qpos = np.asarray(key.qpos)
  root_pos = (0.0, 0.0, 0.0)
  joint_pos: dict[str, float] = {}
  adr = 0
  for joint in spec.joints:
    nq = _JOINT_NQ[joint.type]
    if joint.type == mujoco.mjtJoint.mjJNT_FREE:
      root_pos = tuple(float(v) for v in qpos[adr : adr + 3])  # type: ignore[assignment]
    else:
      joint_pos[re.escape(joint.name) + "$"] = float(qpos[adr])
    adr += nq
  return root_pos, joint_pos


KANG_FULL_HOME_POS, KANG_FULL_HOME_JOINT_POS = _read_keyframe("home")

# The generator's "home" pose: base at 1.02 m, arms out, legs lightly bent. It
# covers all 82 non-free joints because the leg loops have to close; do not
# reduce it to the actuated subset, since mjlab zero-fills whatever is missing.
INIT_STATE = EntityCfg.InitialStateCfg(
  pos=KANG_FULL_HOME_POS,
  joint_pos=KANG_FULL_HOME_JOINT_POS,
  joint_vel={".*": 0.0},
)

##
# Collision config.
##

# The six sole capsules per foot, named left_foot0_collision .. left_foot10_collision
# to match pal_kangaroo. Excludes the ankle capsules, which stay at condim 1.
_FOOT_REGEX = r"(left|right)_foot\d+_collision$"

FULL_COLLISION = CollisionCfg(
  geom_names_expr=(".*_collision",),
  condim={_FOOT_REGEX: 3, ".*_collision": 1},
  priority={_FOOT_REGEX: 1},
  friction={_FOOT_REGEX: (0.6,)},
)


KANG_FULL_ARTICULATION = EntityArticulationInfoCfg(
  actuators=(
    KANG_FULL_HIP_Z_SLIDERS_ACTUATOR_CFG,
    KANG_FULL_HIP_XY_SLIDERS_L_ACTUATOR_CFG,
    KANG_FULL_HIP_XY_SLIDERS_R_ACTUATOR_CFG,
    KANG_FULL_ANKLE_XY_SLIDERS_L_ACTUATOR_CFG,
    KANG_FULL_ANKLE_XY_SLIDERS_R_ACTUATOR_CFG,
    KANG_FULL_LEG_LENGTH_SLIDERS_ACTUATOR_CFG,
    KANG_FULL_ARMS_ACTUATOR_CFG,
    KANG_FULL_PELVIS_1_ACTUATOR_CFG,
    KANG_FULL_PELVIS_2_ACTUATOR_CFG,
  ),
  soft_joint_pos_limit_factor=0.99,
)


def get_kangaroo_full_robot_cfg() -> EntityCfg:
  return EntityCfg(
    init_state=INIT_STATE,
    collisions=(FULL_COLLISION,),
    spec_fn=get_kangaroo_spec,
    articulation=KANG_FULL_ARTICULATION,
  )


def _build_action_scales(
  articulation: EntityArticulationInfoCfg, exclude: set = frozenset()
) -> tuple[dict, tuple]:
  """Build action scale dict and actuator names from articulation config."""
  scales, names = {}, []
  for a in articulation.actuators:
    e = (
      a.effort_limit
      if isinstance(a.effort_limit, dict)
      else {n: a.effort_limit for n in a.target_names_expr}
    )
    s = (
      a.stiffness
      if isinstance(a.stiffness, dict)
      else {n: a.stiffness for n in a.target_names_expr}
    )
    for n in a.target_names_expr:
      if n in e and n in s and s[n] and n not in exclude:
        scales[n] = 0.25 * e[n] / s[n]
        names.append(n)
  return scales, tuple(names)


##
# Final config.
##

KANG_FULL_ACTION_SCALE, KANG_FULL_ACTUATOR_NAMES = _build_action_scales(
  KANG_FULL_ARTICULATION
)


if __name__ == "__main__":
  import mujoco.viewer as viewer
  from mjlab.entity.entity import Entity

  robot = Entity(get_kangaroo_full_robot_cfg())
  viewer.launch(robot.spec.compile())
